### ISSUE TITLE
openlayers map shows up as googlemaps3

### ISSUE THREAD

**Issue by PeterTheOne** [SemanticMediaWiki/SemanticMaps#77] opened 2016-07-12 08:46 UTC
{{#ask:
     [[Category:Locations]]
     |?Has coordinates
     |format=openlayers
    }}

On the current master. With `display_map` it works.

**Comment by JeroenDeDauw** [comment] 2016-07-12 10:20
Tried to confirm on SMW wiki... some error is preventing that tho >_> https://www.semantic-mediawiki.org/w/index.php?title=Special%3AAsk&q=%5B%5BHas+coordinates%3A%3A%2B%5D%5D&po=%3FHas+coordinates&eq=yes&p%5Bformat%5D=openlayers&sort_num=&order_num=ASC&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=...+further+results&p%5Bdefault%5D=&p%5Bgeoservice%5D=geonames&p%5Bwidth%5D=auto&p%5Bheight%5D=350&p%5Bcentre%5D=&p%5Bzoom%5D=13&p%5Blayers%5D=osm-mapnik%2Cosm-cyclemap&p%5Boverlays%5D=&p%5Bsearchmarkers%5D=&p%5Bkml%5D=&p%5Bstaticlocations%5D=&p%5Bshowtitle%5D=1&p%5Btemplate%5D=&p%5Buserparam%5D=&p%5Bactiveicon%5D=&p%5Btitle%5D=Special%3AAsk&p%5Blabel%5D=&p%5Bicon%5D=&p%5Bvisitedicon%5D=&p%5Blines%5D=&p%5Bpolygons%5D=&p%5Bcircles%5D=&p%5Brectangles%5D=&p%5Bwmsoverlay%5D=&p%5Bmaxzoom%5D=&p%5Bminzoom%5D=&eq=yes

**Comment by PeterTheOne** [comment] 2016-07-14 14:18
On http://sandbox.semantic-mediawiki.org/w/index.php?title=Sp%C3%A9cial%3AAsk&q=%5B%5BHas+coordinates%3A%3A%2B%5D%5D&po=%3FHas+coordinates%0D%0A&eq=yes&p%5Bformat%5D=googlemaps3&sort_num=&order_num=ASC&p%5Bsource%5D=&p%5Blimit%5D=&p%5Boffset%5D=&p%5Blink%5D=all&p%5Bsort%5D=&p%5Bheaders%5D=show&p%5Bmainlabel%5D=&p%5Bintro%5D=&p%5Boutro%5D=&p%5Bsearchlabel%5D=%26hellip%3B+autres+r%C3%A9sultats&p%5Bdefault%5D=&p%5Bgeoservice%5D=geonames&p%5Bwidth%5D=auto&p%5Bheight%5D=350&p%5Bcentre%5D=&p%5Bzoom%5D=14&p%5Btype%5D=roadmap&p%5Bzoomstyle%5D=default&p%5Btypestyle%5D=default&p%5Bpoi%5D=1&p%5Bclustergridsize%5D=60&p%5Bclustermaxzoom%5D=20&p%5Bclusterzoomonclick%5D=1&p%5Bclusteraveragecenter%5D=1&p%5Bclusterminsize%5D=2&p%5Btilt%5D=0&p%5Bimageoverlays%5D=&p%5Bkml%5D=&p%5Bgkml%5D=&p%5Bfusiontables%5D=&p%5Bsearchmarkers%5D=&p%5Bstaticlocations%5D=&p%5Bshowtitle%5D=1&p%5Btemplate%5D=&p%5Buserparam%5D=&p%5Bactiveicon%5D=&p%5Bajaxcoordproperty%5D=Has+coordinates&p%5Bajaxquery%5D=&p%5Btitle%5D=&p%5Blabel%5D=&p%5Bicon%5D=&p%5Bvisitedicon%5D=&p%5Blines%5D=&p%5Bpolygons%5D=&p%5Bcircles%5D=&p%5Brectangles%5D=&p%5Bwmsoverlay%5D=&p%5Bmaxzoom%5D=&p%5Bminzoom%5D=&eq=yes I get `Fatal error: Call to a member function addTrackingCategory() on null in /var/www/htdocs/mw/02100/w/includes/parser/Parser.php on line 4402`

**Comment by kghbln** [comment] 2016-07-14 15:34
> Fatal error: Call to a member function addTrackingCategory() on null in /.../w/includes/parser/Parser.php on line 4402

This sounded familiar: https://phabricator.wikimedia.org/T137901

**Comment by kghbln** [comment] 2016-07-14 15:42
That's what I get, so it seems that there is an issue with the ParamProcessor:
```
[Thu Jul 14 14:27:15.972681 2016] [:error] [pid 30845] [client 77.247.181.162:57075] PHP Warning:  Invalid argument supplied for foreach() in /.../w/vendor/param-processor/param-processor/src/ParamDefinition.php on line 522, referer: http://sandbox.semantic-mediawiki.org/wiki/Ajaxquery
```

**Comment by JeroenDeDauw** [comment] 2016-07-15 11:54
I've created a new release of ParamProcessor now and expect this issue to be ... different now, possibly fixed.

**Comment by kghbln** [comment] 2016-07-15 15:06
Affirmative, the issue with ParamPrecessor is fixed with version 1.3.0. However, [T137901](https://phabricator.wikimedia.org/T137901) still gives pain but as stated they have no idea what this code does either. Keeping fingers crossed for a fix.

**Comment by kghbln** [comment] 2016-07-15 15:12
Back to the original issue. I cannot confirm that "openlayers" shows up as "googlemaps" but there is an issue with "openlayers" as one can see on the [example page](http://sandbox.semantic-mediawiki.org/wiki/SMissue77) I created: No results are rendered for "openlayers".

**Comment by kghbln** [comment] 2016-07-15 20:18
Now after setting `$egMapsEnableCategory = false;` we can verify that "googlemaps" is used rather than "openlayers" when using special page "Special:Ask". Thus my previous post relates to another issue.

**Comment by kghbln** [comment] 2016-07-15 20:29
> No results are rendered for "openlayers".

Now tracked with issue https://github.com/SemanticMediaWiki/SemanticMaps/issues/80

**Comment by JeroenDeDauw** [comment] 2016-08-16 11:32
So can we close this?

For some reason the OpenLayers format is not showing up in the format selection box on the sandbox's Special:Ask... http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Requ%C3%AAter Any idea what the deal with that is?

**Comment by kghbln** [comment] 2016-08-16 11:42
> So can we close this?

No since my talk was referring to another issue. This one is still here.

**Comment by JeroenDeDauw** [comment] 2016-09-02 01:58
I've had a look at this issue though did not see any reason why OpenLayers should fail. Reworked some stuff, might fix the issue... https://github.com/SemanticMediaWiki/SemanticMaps/pull/105

**Comment by JeroenDeDauw** [comment] 2016-09-07 07:17
Apparently I did not break all the things with that PR as I kinda feared, though the issue is also not fixed.

What I suggest doing to fix this issue is just drop the whole "service feature registration" mechanism. Or rather, stop using it for the query printers in Semantic Maps. Registering the printers directly is much simpler. See `SMQueryPrinters` and `SemanticMaps.php`

**Comment by JeroenDeDauw** [comment] 2016-09-13 14:22
A step towards that: https://github.com/SemanticMediaWiki/SemanticMaps/pull/109

**Comment by JeroenDeDauw** [comment] 2016-09-13 15:28
To refactor the initialization code to something sane, SMW needs to provide a way to register query printers in a way that allows for dependency injection. Did some superficial cleanup already before making that addition to the SMW API: https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1834 https://github.com/SemanticMediaWiki/SemanticMediaWiki/pull/1835

**Comment by JeroenDeDauw** [comment] 2016-09-13 18:46
As per comment on https://github.com/SemanticMediaWiki/SemanticMaps/pull/112, this is fixed

**Closed by JeroenDeDauw** 2016-09-13 18:46 UTC
Labels: bug

**Comment by kghbln** [comment] 2016-09-13 19:07
> As per comment on #112, this is fixed

? On sandbox I still get googlemaps

**Comment by JeroenDeDauw** [comment] 2016-09-13 19:39
It's showing up on Special:Ask in the list, the format works there, and your example page shows an OL map... 

![ol](https://cloud.githubusercontent.com/assets/146040/18488636/9bc8f80a-79fa-11e6-95b0-ecdfbd45baf1.jpg)

**Comment by kghbln** [comment] 2016-09-13 19:41
> It's showing up on Special:Ask in the list, the format works there, and your example page shows an OL map... 

Yeah, but there are not markers. So it is still broken? No?

**Comment by JeroenDeDauw** [comment] 2016-09-13 19:41
This is still broken: https://github.com/SemanticMediaWiki/SemanticMaps/issues/80

**Comment by kghbln** [comment] 2016-09-13 19:45
> This is still broken: #80

Ah, thanks a bunny, uh bunch.

**Comment by JeroenDeDauw** [comment] 2016-09-13 20:05
![img_1341](https://cloud.githubusercontent.com/assets/146040/18489541/33fc5254-79fe-11e6-9f66-1ddd0ff23229.JPG)
