### ISSUE TITLE
Coordinates in decimal

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticMaps#45] opened 2015-07-24 12:21 UTC
> Hello. We have a wiki where we pass decimal coordinates to infobox, but they are saved as degree, minutes, seconds see. When we query them, they are returned as degree, minutes, seconds. How can we get them in decimal? I have tried "|?coordenadas#decimal", without luck. 

https://semantic-mediawiki.org/wiki/Thread:Help_talk:Type_Geographic_coordinate/Coordinates_in_decimal

**Comment by mwjames** [comment] 2015-07-24 12:25
After a quick look into `SMGeoCoordsValue`, I could not find any reference to `$this->m_outformat` which would enable to select a specific output format therefore `"|?coordenadas#decimal"` is currently not supported.

@JeroenDeDauw Did I miss something?

The output format is set in `SMWResultArray::getNextDataValue`

```php
	$dv = \SMW\DataValueFactory::getInstance()->newDataItemValue( $di, $diProperty );
	if ( $this->mPrintRequest->getOutputFormat() ) {
	$dv->setOutputFormat( $this->mPrintRequest->getOutputFormat() );
	}
	return $dv;
```

**Comment by JeroenDeDauw** [comment] 2015-07-24 20:25
`"|?coordenadas#decimal"` is indeed not currently supported.

**Comment by JeroenDeDauw** [comment] 2015-07-24 20:29
There is a setting to change this though:

```php
	# Enum. The default output format of coordinates.
	# Possible values: Maps_COORDS_FLOAT, Maps_COORDS_DMS, Maps_COORDS_DM, Maps_COORDS_DD
	$GLOBALS['smgQPCoodFormat'] = $GLOBALS['egMapsCoordinateNotation'];
	
	# Boolean. Indicates if coordinates should be outputted in directional notation by default.
	$GLOBALS['smgQPCoodDirectional'] = $GLOBALS['egMapsCoordinateDirectional'];
```

**Comment by kghbln** [comment] 2015-07-24 21:00
So this is a matter of documenting things?

**Comment by JeroenDeDauw** [comment] 2015-07-24 22:59
Guess so. Though IIRC this was already documented somehow at some point... Though perhaps that was just the docs saying to look at this file. After all, the comments in there are geared towards site admins that want to use those settings.

**Comment by JeroenDeDauw** [comment] 2016-04-02 21:28
Shall we close this?

**Comment by kghbln** [comment] 2016-04-02 22:44
Well, this still has to be documented. Oh man ...

**Comment by krabina** [comment] 2017-03-01 14:53
In my test wiki, changing the default to 
$smgQPCoodFormat  = 'Maps_COORDS_FLOAT';
resulted in errors. 

Unexpected non-MediaWiki exception encountered, of type "InvalidArgumentException"
[d1478d72] /index.php?title=Attribut:Koordinaten Exception from line 202 of .../vendor/data-values/geo/src/Formatters/GeoCoordinateFormatter.php: Invalid coordinate format specified in the options
Backtrace:
#0 .../vendor/data-values/geo/src/Formatters/GeoCoordinateFormatter.php(154): DataValues\Geo\Formatters\GeoCoordinateFormatter->formatCoordinate(double, double)
#1.../vendor/data-values/geo/src/Formatters/GeoCoordinateFormatter.php(137): DataValues\Geo\Formatters\GeoCoordinateFormatter->formatLatitude(double, double)
#2 .../vendor/data-values/geo/src/Formatters/GeoCoordinateFormatter.php(115): DataValues\Geo\Formatters\GeoCoordinateFormatter->formatLatLongValue(DataValues\Geo\Values\LatLongValue, integer)
#3 .../extensions/SemanticMaps/src/SM_GeoCoordsValue.php(72): DataValues\Geo\Formatters\GeoCoordinateFormatter->format(DataValues\Geo\Values\LatLongValue)
#4 .../extensions/SemanticMaps/src/SM_GeoCoordsValue.php(36): SMGeoCoordsValue->getFormattedCoord(SMWDIGeoCoord)
#5 .../extensions/SemanticMediaWiki/includes/datavalues/SMW_DataValue.php(209): SMGeoCoordsValue->loadDataItem(SMWDIGeoCoord)
#6 .../extensions/SemanticMediaWiki/src/DataValueFactory.php(147): SMWDataValue->setDataItem(SMWDIGeoCoord)
#7 .../extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(254): SMW\DataValueFactory->newDataValueByItem(SMWDIGeoCoord, SMW\DIProperty)
#8 .../extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(191): SMWPropertyPage->subjectObjectList(array)
#9 .../extensions/SemanticMediaWiki/includes/articlepages/SMW_PropertyPage.php(43): SMWPropertyPage->getPropertyValueList()
#10 .../extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php(175): SMWPropertyPage->getHtml()
#11 .../extensions/SemanticMediaWiki/includes/articlepages/SMW_OrderedListPage.php(92): SMWOrderedListPage->showList()
#12 .../includes/actions/ViewAction.php(44): SMWOrderedListPage->view()
#13 .../includes/Wiki.php(487): ViewAction->show()
#14 .../includes/Wiki.php(285): MediaWiki->performAction(SMWPropertyPage, Title)
#15 .../includes/Wiki.php(647): MediaWiki->performRequest()
#16 .../includes/Wiki.php(506): MediaWiki->main()
#17 .../index.php(46): MediaWiki->run()
#18 {main}

**Comment by JeroenDeDauw** [comment] 2017-03-01 17:02
Something must have changed in the geo component... @thiemowmde any idea?

**Comment by JeroenDeDauw** [comment] 2017-03-01 17:09
I had a look at the code and I'm not seeing anything that should cause the error.

`Maps_COORDS_FLOAT` is "float", and so is `GeoCoordinateFormatter::TYPE_FLOAT`...

@krabina can you please open a new issue in which you specify the versions of the software you use?

**Comment by thiemowmde** [comment] 2017-03-01 17:26
It looks like the option is not passed correctly. It's most probably null or an empty string.

**Comment by krabina** [comment] 2017-03-09 10:08
My versions are:
MediaWiki 	1.23.13
PHP 	5.5.38 (cgi-fcgi)
MySQL 	5.5.54-cll
Semantic MediaWiki	2.4.1
Maps	3.7.0
Semantic Maps	3.3

**Comment by JeroenDeDauw** [comment] 2019-01-20 14:38
I suspect this was fixed some time ago in Maps. If not, please file a new issue for Maps with steps to reproduce. https://github.com/JeroenDeDauw/Maps

**Closed by JeroenDeDauw** 2019-01-20 14:38 UTC
Labels: newcomer, question
